### ISSUE TITLE
播放原声第二个音频后，在录音时就会程序崩。

### ISSUE THREAD

**Issue by YunliangYu** [hackist/ilip#39]
只要是播放第二个原声音频，无论第几道题，都会无法在录音。

**Comment by bartuer** [comment]
add log

**Comment by bartuer** [comment]
[ { _fileName: '/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/http-errors/index.js',
    _functionName: 'ClientError',
    _lineNumber: '1',
    _columnNumber: '1868',
    _msg: '    at ClientError@/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/http-errors/index.js:1:1868' },
  { _fileName: '/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/http-errors/index.js',
    _functionName: 'createError',
    _lineNumber: '1',
    _columnNumber: '1210',
    _msg: '    at createError@/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/http-errors/index.js:1:1210' },
  { _fileName: '/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/send/index.js',
    _functionName: 'error',
    _lineNumber: '1',
    _columnNumber: '3856',
    _msg: '    at error@/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/send/index.js:1:3856' },
  { _fileName: '/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/send/index.js',
    _functionName: 'send',
    _lineNumber: '1',
    _columnNumber: '9197',
    _msg: '    at send@/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/send/index.js:1:9197' },
  { _fileName: '/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/send/index.js',
    _functionName: 'onstat',
    _lineNumber: '1',
    _columnNumber: '10028',
    _msg: '    at onstat@/private/var/mobile/Containers/Data/Application/1714A0CD-C3A4-4583-8B8A-00514D4C6A81/Library/NoCloud/server/backend/node_modules/send/index.js:1:10028' },
  { _fileName: 'fs.js',
    _functionName: '$b/<',
    _lineNumber: '85',
    _columnNumber: '8',
    _msg: '    at $b/<@fs.js:85:8' },
  toString: [Function] ]

**Comment by bartuer** [comment]
#37 dup?

**Comment by bartuer** [comment]
play audio session will break record

**Comment by bartuer** [comment]
should be audio format problem, change sample rate from 44100 -> 22050 can fix it

**Comment by bartuer** [comment]
插耳机仍有问题。
